### PR TITLE
Toggle feature to the section issue #33

### PR DESCRIPTION
**Pull request by aditiverma-21**
The effect in this section is done and optimistic.

### CODE REVIEW

**Review by ChandelAnish — COMMENTED** [review]
on mouse hover the heading is not visible , it don't find it necessary.
image

you must describe changes and share screenshot for reference.
what is toogle feature you want to implements??

**Comment by aditiverma-21** [comment]
Let me add SS and videos

**Comment by aditiverma-21** [comment]
@ChandelAnish I have made changes in this section

**Comment by aditiverma-21** [comment]
@ChandelAnish Can you please add labels and level to this PR?

**Comment by ChandelAnish** [comment]
on hover the heading turns white due to which it is not visible 

https://github.com/user-attachments/assets/277428d0-32d2-4a07-9596-cee05aa53c52

**Comment by aditiverma-21** [comment]
I will chnage that too.

**Comment by aditiverma-21** [comment]
Please assign and label these

**Comment by ChandelAnish** [comment]
> Please assign and label these

done

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/ae6aef3c-80e1-41d9-822c-ac2417fc0c00

@ChandelAnish Please check the demo video. and tell if there are any adjustments.

no need of color change effect on hover

**Comment by aditiverma-21** [comment]
@ChandelAnish Please check this

**Comment by ChandelAnish** [comment]
still same issue
https://github.com/user-attachments/assets/46c01c8f-9a3d-4434-944a-68215343436b

**Comment by aditiverma-21** [comment]
@ChandelAnish I will change that too by today thank you for telling me.

**Comment by ChandelAnish** [comment]
still disappear 
image

**Comment by aditiverma-21** [comment]
@ChandelAnish I have made new PR please check

**Pull request closed without merging**
