### PR TITLE
Feature/signup UI

### LINKED ISSUE #9: Improve sign up page UI
Enhance the UI/UX of the sign-up page, ensuring it is responsive across all devices and making it visually appealing and interactive.

### PR DESCRIPTION
**Pull request by ShivanshPlays**
closes #9 

Here is what I did.

1. deleted the last fork
2. forked the latest repo as of today
3. only added changes, did not modify any existing js
4. raised this PR

image

Because of the issues that my last PR created, I have created this new PR and only made the changes in the UI.....

NOTE: I was not able to find the same password check that @ChandelAnish was saying is not present in the master branch that I have forked, so maybe some other PR that had been merged created that problem, rest assured this time I have only performed UI changes.

### CODE REVIEW

**Comment by ShivanshPlays** [comment]
Hi @ChandelAnish @sanjay-kv please review

**Review by ChandelAnish — COMMENTED** [review]
no error message displaying
image


the current version successfully handles all the error, familiarize with the code and then do the required changes
image

**Comment by ChandelAnish** [comment]
make a new branch from latest of dev-gssoc and perform changes in the client/signup-page directory

**Comment by ShivanshPlays** [comment]
image
my fork is up to date and there are no merge conflicts....also this pr is targetting the dev-gssoc branch only , I dont understand what you require here?

**Pull request closed without merging**
