### PR TITLE
Update hover colours style.css

### PR DESCRIPTION
**Pull request by aditiverma-21**
Please Check the updates

### CODE REVIEW

**Comment by mailech** [comment]
hey @aditiverma-21 / @ChandelAnish the updates u have done are well but not up to the mark. The hovering updates are inadequate. i would like to contribute to the enhancing of the website layouts and updates and would like to make a few animations.



https://github.com/user-attachments/assets/5c7c81f2-71bd-448d-86aa-c34d403efa97

**Comment by aditiverma-21** [comment]
Please add labels to this PR

**Comment by aditiverma-21** [comment]
@sanjay-kv @ChandelAnish Will I get labels on this PR?

**Comment by sanjay-kv** [comment]
I can see this is closed wihtout merging, so you wont get it,

**Pull request closed without merging**
