### PR TITLE
made the login page responsive and did some minor changes

### PR DESCRIPTION
**Pull request by Ayush215mb**
I am creating the PR request in the dev-gssoc branch as you said.
please accept it asap so that i can move on and work on other project as well.

### CODE REVIEW

**Comment by Ayush215mb** [comment]
also please add the hacktober and gssoc label

**Comment by Ayush215mb** [comment]
@ChandelAnish Please accept it asap.

**Review by ChandelAnish — APPROVED** [review]

**Comment by Ayush215mb** [comment]
@ChandelAnish why You haven't added any labels?????

**Comment by Ayush215mb** [comment]
@ChandelAnish Add the labels here asap or hacktoberfest and gssoc will not count this contribution.

**Comment by Ayush215mb** [comment]
The issue assigned to me was #41 .

**Pull request merged**
