### PR TITLE
[Feature Enhancement] : ✨Dark mode toggle added ✨ (issue #7) 

### PR DESCRIPTION
**Pull request by trahulprabhu38**
the feature is implemented and working, please do review it.
Thank you!

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@ChandelAnish i made this PR 20 hrs ago , please review it once.

**Comment by T-Rahul-prabhu-38** [comment]
@ChandelAnish  sir can you please review this PR and this was made 1day ago .
this will be very helpful for me leaderboard ranking.
Thank you!

**Review by ChandelAnish — COMMENTED** [review]
text not visiable

image

text not visible due to background image --> you can remove the background of the background image

image

you changed the alignment of this heading :
previously:
image
now:
image

the nav bar is still in light mode : 
image

login component is not matching the theme :
image

the menu is not in dark theme:
image

you have not implemented the dark theme for entire pages many pages are still in light mode although toggled to dark mode

the text in side the bar must be white always and place the dark mode toggle button in beside the hireHUB logo
image

remove the grey background color
image

the below tags must always have the text color white
image
image

**Comment by trahulprabhu38** [comment]
ill get this done but is level4 in gssoc-extnd?

**Comment by trahulprabhu38** [comment]
i think its better to assign just level 3.

**Comment by ChandelAnish** [comment]
@T-Rahul-prabhu-38 i have tagged this issue level4 since it requires so many changes. Perform all these things and PR

**Comment by trahulprabhu38** [comment]
sure

**Comment by ChandelAnish** [comment]
@T-Rahul-prabhu-38 you must sync you repo to the latest and then do changes

**Comment by trahulprabhu38** [comment]
sure sir ill do that.

**Comment by Ankitha2130** [comment]
I can work on this issue. Please assign it to me

**Pull request closed without merging**
