### PR TITLE
added testimonial section

### PR DESCRIPTION
**Pull request by ketanop321**
Added a simple testimonial section with hover effect
 issue:- #28 

https://github.com/user-attachments/assets/36267f14-1ac9-473f-bd2a-7ed025cdfef0

@ChandelAnish can you check it again please sir

please also add all necessary label

### CODE REVIEW

**Comment by Ketanop321** [comment]
issue #28 

> Adde a simple testimonial section image

**Comment by Ketanop321** [comment]
> Adde a simple testimonial section with hover effect
 image

**Review by ChandelAnish — COMMENTED** [review]
-->give some border radius
-->add some more testimonials and each testimonial moves in a smooth, sliding motion, keeping the content fresh and engaging.
-->make the middle testimonial little bigger
-->add images too

image

**Comment by Gamerking177** [comment]
@ChandelAnish  sir plss add lebel also before merge this issue

**Review by ChandelAnish — COMMENTED** [review]
I intended for the testimonials to continuously move in animations, with a maximum of 3 testimonials displayed at once. This can be achieved by using overflow hidden and ensuring responsiveness.

**Pull request closed without merging**
