### PR TITLE
Improve The Navbar

### PR DESCRIPTION
**Pull request by sambedan1**
Before:-
Screenshot 2024-10-04 010046
After:-
Screenshot 2024-10-04 011607

### CODE REVIEW

**Comment by sambedan1** [comment]
please add the hactoberfest tag

**Review by ChandelAnish — COMMENTED** [review]
make it responsive , remove the horizontal scroll and fallow green - white color scheme

image

**Comment by sambedan1** [comment]
ok

**Comment by sambedan1** [comment]
#done 
make it responsive , remove the horizontal scroll and fallow green - white color scheme
please check it and add the tag

**Review by ChandelAnish — COMMENTED** [review]
signup link is not present

image

**Comment by sambedan1** [comment]
Screenshot 2024-10-04 224329

**Comment by sambedan1** [comment]
it was present

**Comment by sambedan1** [comment]
Please assign and label these

**Review by ChandelAnish — COMMENTED** [review]
not responsive

image

**Pull request closed without merging**
