### PR TITLE
✨features updated✨(issue #7)

### PR DESCRIPTION
**Pull request by trahulprabhu38**
out of 7 of the fixes u asked me to do i have fixed 4 of them , the main one is a navbar which is done in bootstrap and the code for navbar is completelty messed up for differnt pages. I couldnt change any bootstrap issues , but the CSS/HTML issues have been fixed.

### CODE REVIEW

**Comment by trahulprabhu38** [comment]
@ChandelAnish  can you please review this , thank you:)

**Comment by T-Rahul-prabhu-38** [comment]
@ChandelAnish bhaiya can you check this PR.

**Comment by T-Rahul-prabhu-38** [comment]
@ChandelAnish  can you please review this for PR.

**Comment by trahulprabhu38** [comment]
@ChandelAnish  can you please review this for PR. and add the level aswell sir , that day u had assigned it level4

**Review by ChandelAnish — COMMENTED** [review]
icons are removed in dark mode
https://github.com/user-attachments/assets/b9a14498-8229-4493-8cc2-ccd30699c444

still heading is shifted right
Screenshot 2024-10-08 223942


text is not readable and component must be as previous
Screenshot 2024-10-08 223957

**Review by ChandelAnish — COMMENTED** [review]
text not visible due to white text colcor
image

make this login card as it was earlier
image

remove the extra margin
image

you need to PR on the dev-gssoc branch

**Comment by mailech** [comment]
hey @T-Rahul-prabhu-38 / @ChandelAnish the feature you have added it well but the structure have been changed. i would like to rebuild it

**Pull request closed without merging**
